language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: <YOUR ENCRYPTED KEY HERE>
  app: <Full Stack Capstone>
  on:
    repo: <https://github.com/calebxblackwell/Full-Stack-Capstone>
